from typing import Any

GENE_ANNOTATIONS: dict[str, dict[str, Any]] = {
    "EGFR": {
        "symbol": "EGFR",
        "name": "Epidermal Growth Factor Receptor",
        "locus": "Chr 7p11.2",
        "ensembl_id": "ENSG00000146648",
        "uniprot_id": "P00533",
        "pdb_id": "1M17",
        "druggability": "Tier 1: FDA Approved TKI Target",
        "role": "Receptor Tyrosine Kinase (RTK) Initiator",
        "hotspots": [
            "C797S (Exon 20 3rd-Gen TKI Resistance)",
            "T790M (1st/2nd-Gen Gatekeeper Mutation)",
            "L858R (Exon 21 Sensitizing Driver)",
            "Exon 19 In-Frame Deletion (ELREA)",
            "G719X (Exon 18 Atypical Activation)",
        ],
        "pathways": [
            "RAS/RAF/MEK/ERK Cascade",
            "PI3K/AKT/mTOR Survival Axis",
            "STAT3 Signaling",
        ],
    },
    "MET": {
        "symbol": "MET",
        "name": "MET Proto-Oncogene Receptor Tyrosine Kinase",
        "locus": "Chr 7q31.2",
        "ensembl_id": "ENSG00000105976",
        "uniprot_id": "P08581",
        "pdb_id": "3R7O",
        "druggability": "Tier 1: FDA Approved TKI Target",
        "role": "RTK Bypass Hyperactivation & HGF Receptor",
        "hotspots": [
            "MET Gene Amplification (Off-Target RTK Bypass)",
            "Exon 14 Splice Site Skipping (METex14)",
            "D1228N / Y1230C (Type I TKI Solvent Front Resistance)",
            "L1195V (Kinase Activation Loop Mutation)",
        ],
        "pathways": [
            "ERBB3 Trans-Phosphorylation",
            "FAK Cell Motility Axis",
            "PI3K Parallel Survival",
        ],
    },
    "ERBB2": {
        "symbol": "ERBB2",
        "name": "Erb-B2 Receptor Tyrosine Kinase 2 (HER2)",
        "locus": "Chr 17q12",
        "ensembl_id": "ENSG00000141736",
        "uniprot_id": "P04626",
        "pdb_id": "1N8Z",
        "druggability": "Tier 1: FDA Approved mAb & ADC Target",
        "role": "RTK Heterodimerization Partner",
        "hotspots": [
            "HER2 Gene Amplification / Overexpression",
            "Exon 20 YVMA Insertion",
            "L755S (Kinase Domain Lapatinib Resistance)",
            "S310F (Extracellular Domain Hotspot)",
        ],
        "pathways": [
            "HER2/HER3 Heterodimer Signaling",
            "PI3K/AKT Pathway",
            "MAPK Cascade",
        ],
    },
    "ALK": {
        "symbol": "ALK",
        "name": "ALK Receptor Tyrosine Kinase",
        "locus": "Chr 2p23.2",
        "ensembl_id": "ENSG00000171094",
        "uniprot_id": "Q9UM73",
        "pdb_id": "3L9P",
        "druggability": "Tier 1: FDA Approved TKI Target",
        "role": "Oncogenic Fusion Kinase (EML4-ALK)",
        "hotspots": [
            "EML4-ALK Translocation / Fusion Variant 1/3",
            "G1202R (Solvent Front Master Resistance)",
            "L1196M (Gatekeeper Mutation)",
            "I1171N/T (Alectinib Resistance Variant)",
        ],
        "pathways": ["STAT3 Survival Pathway", "RAS/MAPK Axis", "PLCgamma Signaling"],
    },
    "KRAS": {
        "symbol": "KRAS",
        "name": "KRAS Proto-Oncogene GTPase",
        "locus": "Chr 12p12.1",
        "ensembl_id": "ENSG00000133703",
        "uniprot_id": "P01116",
        "pdb_id": "6OIM",
        "druggability": "Tier 1: FDA Approved Covalent Target",
        "role": "Small GTPase Molecular Switch",
        "hotspots": [
            "G12C (Switch-II Covalent Target)",
            "G12D / G12V (Constitutive Active GTP-bound)",
            "Y96D (Sotorasib Switch-II Pocket Resistance)",
            "Q61K / Q61R (Glutamine 61 Catalytic Loss)",
        ],
        "pathways": [
            "RAF/MEK/ERK Signaling",
            "PI3K/PDK1/AKT Axis",
            "RAL-GEF Effector Cascade",
        ],
    },
    "BRAF": {
        "symbol": "BRAF",
        "name": "BRAF Serine/Threonine Kinase",
        "locus": "Chr 7q34",
        "ensembl_id": "ENSG00000157764",
        "uniprot_id": "P15056",
        "pdb_id": "4EB9",
        "druggability": "Tier 1: FDA Approved Kinase Target",
        "role": "MAPK Pathway Central Signal Node",
        "hotspots": [
            "V600E (Class 1 Monomeric Hyperactivation)",
            "V600K / V600R (Exon 15 Hotspots)",
            "BRAF Splice Variants / Homodimer Paradox",
            "L597V / K601E (Class 2 Dimer Activation)",
        ],
        "pathways": [
            "MEK1/2 (MAP2K1/2) Phosphorylation",
            "ERK1/2 Translocation",
            "Cyclin D1 Transcription",
        ],
    },
    "PIK3CA": {
        "symbol": "PIK3CA",
        "name": "PI3K Catalytic Subunit Alpha",
        "locus": "Chr 3q26.32",
        "ensembl_id": "ENSG00000121879",
        "uniprot_id": "P42336",
        "pdb_id": "4L23",
        "druggability": "Tier 1: FDA Approved Inhibitor Target",
        "role": "Lipid Kinase PIP3 Generator",
        "hotspots": [
            "H1047R (Exon 20 Kinase Domain Hotspot)",
            "E542K / E545K (Exon 9 Helical Domain)",
            "C420R (C2 Domain Membrane Interaction)",
        ],
        "pathways": [
            "PIP3 Production at Plasma Membrane",
            "PDK1 & AKT1 Activation",
            "mTORC1 Translation",
        ],
    },
    "ESR1": {
        "symbol": "ESR1",
        "name": "Estrogen Receptor 1",
        "locus": "Chr 6q25.1",
        "ensembl_id": "ENSG00000091831",
        "uniprot_id": "P03372",
        "pdb_id": "1ERE",
        "druggability": "Tier 1: FDA Approved SERD Target",
        "role": "Nuclear Hormone Receptor Transcription Factor",
        "hotspots": [
            "Y537S / Y537N (Ligand-Independent Activation)",
            "D538G (Exon 8 LBD Resistance Hotspot)",
            "E380Q (Helical Domain Mutation)",
        ],
        "pathways": [
            "Estrogen Response Element (ERE) Genes",
            "Cyclin D1 & CDK4/6 Cell Cycle",
            "MYC Transcription",
        ],
    },
    "ABL1": {
        "symbol": "ABL1",
        "name": "ABL1 Non-Receptor Tyrosine Kinase",
        "locus": "Chr 9q34.12",
        "ensembl_id": "ENSG00000097007",
        "uniprot_id": "P00519",
        "pdb_id": "2GQG",
        "druggability": "Tier 1: FDA Approved TKI Target",
        "role": "Oncogenic Fusion Protein (BCR-ABL1)",
        "hotspots": [
            "T315I (Gatekeeper Master Steric Clash)",
            "E255K / Y253F (P-Loop ATP Binding Hotspot)",
            "F317L (Dasatinib Resistance Mutation)",
            "H396P (Activation Loop Mutation)",
        ],
        "pathways": [
            "STAT5 Leukemogenic Signaling",
            "CRKL Adaptor Phosphorylation",
            "PI3K/AKT Survival Axis",
        ],
    },
    "CDK4": {
        "symbol": "CDK4",
        "name": "Cyclin Dependent Kinase 4",
        "locus": "Chr 12q14.1",
        "ensembl_id": "ENSG00000135446",
        "uniprot_id": "P11802",
        "pdb_id": "2C6O",
        "druggability": "Tier 1: FDA Approved CDK4/6 Target",
        "role": "G1/S Phase Transition Kinase",
        "hotspots": [
            "CCND1 (Cyclin D1) Amplification",
            "RB1 Loss of Function (CDK4/6 Resistance)",
            "FAT1 Loss (CDK4/6 Upregulation)",
        ],
        "pathways": [
            "Rb (Retinoblastoma) Phosphorylation",
            "E2F Transcription Release",
            "Cell Cycle Progression",
        ],
    },
    "MAP2K1": {
        "symbol": "MAP2K1",
        "name": "Mitogen-Activated Protein Kinase Kinase 1 (MEK1)",
        "locus": "Chr 15q22.31",
        "ensembl_id": "ENSG00000169032",
        "uniprot_id": "Q02750",
        "pdb_id": "3E8N",
        "druggability": "Tier 1: FDA Approved Allosteric Target",
        "role": "Dual Specificity Kinase (MEK1)",
        "hotspots": [
            "C121S (MEK1 Allosteric Inhibitor Resistance)",
            "P124L / K57E (Activating Helix Mutations)",
            "E203K (Kinase Domain Activation)",
        ],
        "pathways": [
            "ERK1/2 Dual Phosphorylation",
            "AP-1 Transcription Complex",
            "Cell Growth & Survival",
        ],
    },
    "AKT1": {
        "symbol": "AKT1",
        "name": "AKT Serine/Threonine Kinase 1 (PKB)",
        "locus": "Chr 14q32.33",
        "ensembl_id": "ENSG00000142208",
        "uniprot_id": "P31749",
        "pdb_id": "3QKM",
        "druggability": "Tier 1: FDA Approved Kinase Target",
        "role": "Central Survival & Metabolism Kinase",
        "hotspots": [
            "E17K (PH Domain Membrane Hyper-recruitment)",
            "L52R (Allosteric Binding Pocket Mutation)",
            "p-Ser473 / p-Thr308 Hyper-phosphorylation",
        ],
        "pathways": [
            "mTORC1 / S6K Protein Synthesis",
            "FOXO Transcription Factor Inhibition",
            "BAD Antiapoptotic Inactivation",
        ],
    },
    "ROS1": {
        "symbol": "ROS1",
        "name": "ROS Proto-Oncogene 1 Receptor Tyrosine Kinase",
        "locus": "Chr 6q22.1",
        "ensembl_id": "ENSG00000047936",
        "uniprot_id": "P08922",
        "pdb_id": "3ZBF",
        "druggability": "Tier 1: FDA Approved TKI Target",
        "role": "Oncogenic Rearrangement Kinase (CD74-ROS1)",
        "hotspots": [
            "G2032R (Solvent Front Master Resistance)",
            "D2033N (Kinase Binding Pocket Resistance)",
            "S1986Y/F (Gatekeeper Region Mutation)",
        ],
        "pathways": [
            "SHP2 / RAS Activation",
            "PI3K/AKT Pathway",
            "STAT3 Survival Cascade",
        ],
    },
    "RET": {
        "symbol": "RET",
        "name": "RET Proto-Oncogene Kinase",
        "locus": "Chr 10q11.21",
        "ensembl_id": "ENSG00000165731",
        "uniprot_id": "P07949",
        "pdb_id": "2IVT",
        "druggability": "Tier 1: FDA Approved TKI Target",
        "role": "RTK Fusion & Activating Mutation Target",
        "hotspots": [
            "G810R/S (Solvent Front Resistance Variant)",
            "V804M / V804L (Gatekeeper Mutation)",
            "K703E (ATP Binding Pocket Mutation)",
            "KCC6-RET / CCDC6-RET Translocations",
        ],
        "pathways": ["RAS/MAPK Axis", "PI3K/AKT Axis", "PLCgamma Pathway"],
    },
    "NTRK1": {
        "symbol": "NTRK1",
        "name": "Neurotrophic Receptor Tyrosine Kinase 1 (TRKA)",
        "locus": "Chr 1q23.1",
        "ensembl_id": "ENSG00000198400",
        "uniprot_id": "P04629",
        "pdb_id": "4AOJ",
        "druggability": "Tier 1: FDA Approved Agnostic TKI Target",
        "role": "Agnostic Oncogenic Fusion Kinase",
        "hotspots": [
            "G595R (Solvent Front Larotrectinib Resistance)",
            "G667C (xDFG Motif Resistance)",
            "F589L (Gatekeeper Mutation)",
        ],
        "pathways": [
            "TRK Kinase Fusion Signaling",
            "PLCgamma Pathway",
            "PI3K Survival Cascade",
        ],
    },
    "TP53": {
        "symbol": "TP53",
        "name": "Tumor Protein P53",
        "locus": "Chr 17p13.1",
        "ensembl_id": "ENSG00000141510",
        "uniprot_id": "P04637",
        "pdb_id": "1TUP",
        "druggability": "Tier 2: Master Tumor Suppressor",
        "role": "Guardian of the Genome & Apoptosis Regulator",
        "hotspots": [
            "R273H / R273C (DNA Binding Hotspot)",
            "R175H (Conformational Structural Loss)",
            "R248Q / R248W (Contact Hotspot Variant)",
            "Y220C (Small Molecule Reactivation Pocket)",
        ],
        "pathways": [
            "Cell Cycle Arrest (p21/CDKN1A)",
            "BAX/PUMA Pro-Apoptotic Axis",
            "DNA Repair Surveillance",
        ],
    },
    "PTEN": {
        "symbol": "PTEN",
        "name": "Phosphatase and Tensin Homolog",
        "locus": "Chr 10q23.31",
        "ensembl_id": "ENSG00000171862",
        "uniprot_id": "P60484",
        "pdb_id": "1D5R",
        "druggability": "Tier 2: Master Lipid Phosphatase Suppressor",
        "role": "PI3K/AKT De-phosphorylation Brake",
        "hotspots": [
            "Homozygous Genomic Deletion",
            "R130G / R130Q (Phosphatase Catalytic Domain)",
            "C124S (Enzymatic Active Site Inactivation)",
        ],
        "pathways": [
            "PIP3 Dephosphorylation to PIP2",
            "Negative Regulation of AKT Signaling",
            "Cell Migration Control",
        ],
    },
    "GRB2": {
        "symbol": "GRB2",
        "name": "Growth Factor Receptor Bound Protein 2",
        "locus": "Chr 17q25.1",
        "ensembl_id": "ENSG00000177885",
        "uniprot_id": "P62993",
        "pdb_id": "1TZE",
        "druggability": "Tier 3: Bottleneck Adaptor Protein",
        "role": "SH2/SH3 Adaptor Bridge Protein",
        "hotspots": [
            "SH2 Domain Phosphotyrosine Binding Loop",
            "N-terminal SH3 Domain SOS1 Interaction",
            "C-terminal SH3 Domain GAB1 Docking",
        ],
        "pathways": [
            "RTK-to-RAS Signal Coupling",
            "GAB1 Membrane Complex",
            "SOS1 Guanine Exchange",
        ],
    },
    "SOS1": {
        "symbol": "SOS1",
        "name": "Son of Sevenless Homolog 1",
        "locus": "Chr 2p22.1",
        "ensembl_id": "ENSG00000115904",
        "uniprot_id": "Q07889",
        "pdb_id": "6D55",
        "druggability": "Tier 2: Clinical Trial Candidate (SOS1 Inhibitors)",
        "role": "Guanine Nucleotide Exchange Factor (GEF)",
        "hotspots": [
            "GDP-to-GTP Nucleotide Exchange Pocket",
            "Allosteric RAS Binding Site",
            "Nozonanib / BI-3406 Inhibitor Binding Site",
        ],
        "pathways": [
            "KRAS GDP-to-GTP Exchange",
            "RAC1 Signaling Axis",
            "RAS-GTP Activation",
        ],
    },
}


def get_gene_annotation(symbol: str) -> dict[str, Any]:
    """Retrieve curated display metadata without fabricating unknown identifiers."""
    sym_clean = (symbol or "").strip().upper()
    if sym_clean in GENE_ANNOTATIONS:
        return {**GENE_ANNOTATIONS[sym_clean], "source": "curated project metadata"}

    # Unknown values remain unknown. Invented IDs and clinical claims are unsafe.
    return {
        "symbol": sym_clean,
        "name": None,
        "locus": None,
        "ensembl_id": None,
        "uniprot_id": None,
        "pdb_id": None,
        "druggability": "Unknown",
        "role": None,
        "hotspots": [],
        "pathways": [],
        "source": None,
    }
