from typing import Any

GENE_ANNOTATIONS: dict[str, dict[str, Any]] = {
    "EGFR": {
        "symbol": "EGFR",
        "name": "Epidermal Growth Factor Receptor",
        "locus": "Chr 7p11.2",
        "ensembl_id": "ENSG00000146648",
        "uniprot_id": "P00533",
        "pdb_id": "1M17",
        "druggability": "Clinically targeted RTK; regulatory status is indication-specific",
        "role": "Receptor tyrosine kinase involved in growth signaling",
        "hotspots": [
            "C797S (Exon 20 3rd-Gen TKI Resistance)",
            "T790M (1st/2nd-Gen Gatekeeper Mutation)",
            "L858R (Exon 21 Sensitizing Driver)",
            "Exon 19 In-Frame Deletion (ELREA)",
            "G719X (Exon 18 Atypical Activation)",
        ],
        "pathways": [
            "RAS–RAF–MEK–ERK signaling",
            "PI3K–AKT–mTOR signaling",
            "STAT3 Signaling",
        ],
    },
    "MET": {
        "symbol": "MET",
        "name": "MET Proto-Oncogene Receptor Tyrosine Kinase",
        "locus": "Chr 7q31.2",
        "ensembl_id": "ENSG00000105976",
        "uniprot_id": "P08581",
        "pdb_id": "3R7O",
        "druggability": "Clinically targeted RTK; regulatory status is indication-specific",
        "role": "HGF receptor; MET activation can support alternative signaling",
        "hotspots": [
            "MET amplification (alternative signaling during treatment)",
            "Exon 14 Splice Site Skipping (METex14)",
            "D1228N / Y1230C (Type I TKI Solvent Front Resistance)",
            "L1195V (Kinase Activation Loop Mutation)",
        ],
        "pathways": [
            "ERBB3 Trans-Phosphorylation",
            "FAK signaling and cell motility",
            "PI3K–AKT signaling",
        ],
    },
    "ERBB2": {
        "symbol": "ERBB2",
        "name": "Erb-B2 Receptor Tyrosine Kinase 2 (HER2)",
        "locus": "Chr 17q12",
        "ensembl_id": "ENSG00000141736",
        "uniprot_id": "P04626",
        "pdb_id": "1N8Z",
        "druggability": "Clinically targeted receptor; regulatory status is indication-specific",
        "role": "Receptor tyrosine kinase that pairs with other ERBB receptors",
        "hotspots": [
            "HER2 Gene Amplification / Overexpression",
            "Exon 20 YVMA Insertion",
            "L755S (Kinase Domain Lapatinib Resistance)",
            "S310F (Extracellular Domain Hotspot)",
        ],
        "pathways": [
            "HER2/HER3 Heterodimer Signaling",
            "PI3K/AKT Pathway",
            "MAPK signaling",
        ],
    },
    "ALK": {
        "symbol": "ALK",
        "name": "ALK Receptor Tyrosine Kinase",
        "locus": "Chr 2p23.2",
        "ensembl_id": "ENSG00000171094",
        "uniprot_id": "Q9UM73",
        "pdb_id": "3L9P",
        "druggability": "Clinically targeted kinase; regulatory status is indication-specific",
        "role": "Kinase activated by oncogenic fusions such as EML4–ALK",
        "hotspots": [
            "EML4-ALK Translocation / Fusion Variant 1/3",
            "G1202R (solvent-front substitution associated with inhibitor resistance)",
            "L1196M (Gatekeeper Mutation)",
            "I1171N/T (Alectinib Resistance Variant)",
        ],
        "pathways": ["STAT3 signaling", "RAS–MAPK signaling", "PLCγ signaling"],
    },
    "KRAS": {
        "symbol": "KRAS",
        "name": "KRAS Proto-Oncogene GTPase",
        "locus": "Chr 12p12.1",
        "ensembl_id": "ENSG00000133703",
        "uniprot_id": "P01116",
        "pdb_id": "6OIM",
        "druggability": "Clinically targeted protein; regulatory status is indication-specific",
        "role": "Small GTPase that regulates downstream signaling",
        "hotspots": [
            "G12C (Switch-II Covalent Target)",
            "G12D / G12V (Constitutive Active GTP-bound)",
            "Y96D (Sotorasib Switch-II Pocket Resistance)",
            "Q61K / Q61R (Glutamine 61 Catalytic Loss)",
        ],
        "pathways": [
            "RAF/MEK/ERK Signaling",
            "PI3K–PDK1–AKT signaling",
            "RAL-GEF signaling",
        ],
    },
    "BRAF": {
        "symbol": "BRAF",
        "name": "BRAF Serine/Threonine Kinase",
        "locus": "Chr 7q34",
        "ensembl_id": "ENSG00000157764",
        "uniprot_id": "P15056",
        "pdb_id": "4EB9",
        "druggability": "Clinically targeted kinase; regulatory status is indication-specific",
        "role": "Kinase in the MAPK pathway",
        "hotspots": [
            "V600E (Class 1 activating mutation)",
            "V600K / V600R (Exon 15 Hotspots)",
            "BRAF Splice Variants / Homodimer Paradox",
            "L597V / K601E (Class 2 Dimer Activation)",
        ],
        "pathways": [
            "MEK1/2 (MAP2K1/2) Phosphorylation",
            "ERK1/2 Translocation",
            "Cyclin D1 Transcription",
        ],
    },
    "PIK3CA": {
        "symbol": "PIK3CA",
        "name": "PI3K Catalytic Subunit Alpha",
        "locus": "Chr 3q26.32",
        "ensembl_id": "ENSG00000121879",
        "uniprot_id": "P42336",
        "pdb_id": "4L23",
        "druggability": "Clinically targeted enzyme; regulatory status is indication-specific",
        "role": "Lipid kinase that generates PIP3",
        "hotspots": [
            "H1047R (Exon 20 Kinase Domain Hotspot)",
            "E542K / E545K (Exon 9 Helical Domain)",
            "C420R (C2 Domain Membrane Interaction)",
        ],
        "pathways": [
            "PIP3 Production at Plasma Membrane",
            "PDK1 & AKT1 Activation",
            "mTORC1 Translation",
        ],
    },
    "ESR1": {
        "symbol": "ESR1",
        "name": "Estrogen Receptor 1",
        "locus": "Chr 6q25.1",
        "ensembl_id": "ENSG00000091831",
        "uniprot_id": "P03372",
        "pdb_id": "1ERE",
        "druggability": "Clinically targeted receptor; regulatory status is indication-specific",
        "role": "Nuclear Hormone Receptor Transcription Factor",
        "hotspots": [
            "Y537S / Y537N (Ligand-Independent Activation)",
            "D538G (Exon 8 LBD Resistance Hotspot)",
            "E380Q (Helical Domain Mutation)",
        ],
        "pathways": [
            "Estrogen Response Element (ERE) Genes",
            "Cyclin D1 & CDK4/6 Cell Cycle",
            "MYC Transcription",
        ],
    },
    "ABL1": {
        "symbol": "ABL1",
        "name": "ABL1 Non-Receptor Tyrosine Kinase",
        "locus": "Chr 9q34.12",
        "ensembl_id": "ENSG00000097007",
        "uniprot_id": "P00519",
        "pdb_id": "2GQG",
        "druggability": "Clinically targeted kinase; regulatory status is indication-specific",
        "role": "Oncogenic Fusion Protein (BCR-ABL1)",
        "hotspots": [
            "T315I (gatekeeper substitution associated with reduced inhibitor binding)",
            "E255K / Y253F (P-Loop ATP Binding Hotspot)",
            "F317L (Dasatinib Resistance Mutation)",
            "H396P (Activation Loop Mutation)",
        ],
        "pathways": [
            "STAT5 Leukemogenic Signaling",
            "CRKL Adaptor Phosphorylation",
            "PI3K–AKT signaling",
        ],
    },
    "CDK4": {
        "symbol": "CDK4",
        "name": "Cyclin Dependent Kinase 4",
        "locus": "Chr 12q14.1",
        "ensembl_id": "ENSG00000135446",
        "uniprot_id": "P11802",
        "pdb_id": "2C6O",
        "druggability": "Clinically targeted cell-cycle node; regulatory status is indication-specific",
        "role": "G1/S Phase Transition Kinase",
        "hotspots": [
            "CCND1 (Cyclin D1) Amplification",
            "RB1 Loss of Function (CDK4/6 Resistance)",
            "FAT1 Loss (CDK4/6 Upregulation)",
        ],
        "pathways": [
            "Rb (Retinoblastoma) Phosphorylation",
            "E2F Transcription Release",
            "Cell Cycle Progression",
        ],
    },
    "MAP2K1": {
        "symbol": "MAP2K1",
        "name": "Mitogen-Activated Protein Kinase Kinase 1 (MEK1)",
        "locus": "Chr 15q22.31",
        "ensembl_id": "ENSG00000169032",
        "uniprot_id": "Q02750",
        "pdb_id": "3E8N",
        "druggability": "Clinically targeted kinase; regulatory status is indication-specific",
        "role": "Dual Specificity Kinase (MEK1)",
        "hotspots": [
            "C121S (MEK1 Allosteric Inhibitor Resistance)",
            "P124L / K57E (Activating Helix Mutations)",
            "E203K (Kinase Domain Activation)",
        ],
        "pathways": [
            "ERK1/2 Dual Phosphorylation",
            "AP-1 Transcription Complex",
            "Cell Growth & Survival",
        ],
    },
    "AKT1": {
        "symbol": "AKT1",
        "name": "AKT Serine/Threonine Kinase 1 (PKB)",
        "locus": "Chr 14q32.33",
        "ensembl_id": "ENSG00000142208",
        "uniprot_id": "P31749",
        "pdb_id": "3QKM",
        "druggability": "Clinically targeted kinase; regulatory status is indication-specific",
        "role": "Kinase involved in cell survival and metabolism",
        "hotspots": [
            "E17K (increased membrane recruitment through the PH domain)",
            "L52R (Allosteric Binding Pocket Mutation)",
            "Increased phosphorylation at Ser473 or Thr308",
        ],
        "pathways": [
            "mTORC1 / S6K Protein Synthesis",
            "FOXO Transcription Factor Inhibition",
            "BAD Antiapoptotic Inactivation",
        ],
    },
    "ROS1": {
        "symbol": "ROS1",
        "name": "ROS Proto-Oncogene 1 Receptor Tyrosine Kinase",
        "locus": "Chr 6q22.1",
        "ensembl_id": "ENSG00000047936",
        "uniprot_id": "P08922",
        "pdb_id": "3ZBF",
        "druggability": "Clinically targeted kinase; regulatory status is indication-specific",
        "role": "Oncogenic Rearrangement Kinase (CD74-ROS1)",
        "hotspots": [
            "G2032R (solvent-front substitution associated with inhibitor resistance)",
            "D2033N (Kinase Binding Pocket Resistance)",
            "S1986Y/F (Gatekeeper Region Mutation)",
        ],
        "pathways": [
            "SHP2 / RAS Activation",
            "PI3K/AKT Pathway",
            "STAT3 signaling",
        ],
    },
    "RET": {
        "symbol": "RET",
        "name": "RET Proto-Oncogene Kinase",
        "locus": "Chr 10q11.21",
        "ensembl_id": "ENSG00000165731",
        "uniprot_id": "P07949",
        "pdb_id": "2IVT",
        "druggability": "Clinically targeted kinase; regulatory status is indication-specific",
        "role": "Receptor tyrosine kinase activated by fusions or mutations",
        "hotspots": [
            "G810R/S (Solvent Front Resistance Variant)",
            "V804M / V804L (Gatekeeper Mutation)",
            "K703E (ATP Binding Pocket Mutation)",
            "KCC6-RET / CCDC6-RET Translocations",
        ],
        "pathways": ["RAS–MAPK signaling", "PI3K–AKT signaling", "PLCγ signaling"],
    },
    "NTRK1": {
        "symbol": "NTRK1",
        "name": "Neurotrophic Receptor Tyrosine Kinase 1 (TRKA)",
        "locus": "Chr 1q23.1",
        "ensembl_id": "ENSG00000198400",
        "uniprot_id": "P04629",
        "pdb_id": "4AOJ",
        "druggability": "Clinically targeted kinase; regulatory status is indication-specific",
        "role": "Receptor tyrosine kinase activated by oncogenic fusions",
        "hotspots": [
            "G595R (Solvent Front Larotrectinib Resistance)",
            "G667C (xDFG Motif Resistance)",
            "F589L (Gatekeeper Mutation)",
        ],
        "pathways": [
            "TRK Kinase Fusion Signaling",
            "PLCgamma Pathway",
            "PI3K–AKT signaling",
        ],
    },
    "TP53": {
        "symbol": "TP53",
        "name": "Tumor Protein P53",
        "locus": "Chr 17p13.1",
        "ensembl_id": "ENSG00000141510",
        "uniprot_id": "P04637",
        "pdb_id": "1TUP",
        "druggability": "Tumor suppressor; no blanket druggability claim",
        "role": "Tumor suppressor involved in DNA-damage responses and apoptosis",
        "hotspots": [
            "R273H / R273C (DNA Binding Hotspot)",
            "R175H (Conformational Structural Loss)",
            "R248Q / R248W (Contact Hotspot Variant)",
            "Y220C (Small Molecule Reactivation Pocket)",
        ],
        "pathways": [
            "Cell Cycle Arrest (p21/CDKN1A)",
            "BAX and PUMA regulation of apoptosis",
            "DNA Repair Surveillance",
        ],
    },
    "PTEN": {
        "symbol": "PTEN",
        "name": "Phosphatase and Tensin Homolog",
        "locus": "Chr 10q23.31",
        "ensembl_id": "ENSG00000171862",
        "uniprot_id": "P60484",
        "pdb_id": "1D5R",
        "druggability": "Tumor suppressor; pathway relevance does not imply direct druggability",
        "role": "Tumor suppressor that limits PI3K–AKT signaling",
        "hotspots": [
            "Homozygous Genomic Deletion",
            "R130G / R130Q (Phosphatase Catalytic Domain)",
            "C124S (Enzymatic Active Site Inactivation)",
        ],
        "pathways": [
            "PIP3 Dephosphorylation to PIP2",
            "Negative Regulation of AKT Signaling",
            "Cell Migration Control",
        ],
    },
    "GRB2": {
        "symbol": "GRB2",
        "name": "Growth Factor Receptor Bound Protein 2",
        "locus": "Chr 17q25.1",
        "ensembl_id": "ENSG00000177885",
        "uniprot_id": "P62993",
        "pdb_id": "1TZE",
        "druggability": "Adaptor protein; direct druggability is context-specific",
        "role": "Adaptor protein linking activated receptors to downstream signaling",
        "hotspots": [
            "SH2 Domain Phosphotyrosine Binding Loop",
            "N-terminal SH3 Domain SOS1 Interaction",
            "C-terminal SH3 Domain GAB1 Docking",
        ],
        "pathways": [
            "RTK-to-RAS Signal Coupling",
            "GAB1 Membrane Complex",
            "SOS1 Guanine Exchange",
        ],
    },
    "SOS1": {
        "symbol": "SOS1",
        "name": "Son of Sevenless Homolog 1",
        "locus": "Chr 2p22.1",
        "ensembl_id": "ENSG00000115904",
        "uniprot_id": "Q07889",
        "pdb_id": "6D55",
        "druggability": "SOS1 inhibitors are under clinical investigation; status depends on the specific drug and cancer type",
        "role": "Guanine Nucleotide Exchange Factor (GEF)",
        "hotspots": [
            "GDP-to-GTP Nucleotide Exchange Pocket",
            "Allosteric RAS Binding Site",
            "BI-3406 allosteric inhibitor binding site",
        ],
        "pathways": [
            "KRAS GDP-to-GTP Exchange",
            "RAC1 signaling",
            "RAS-GTP Activation",
        ],
    },
}


def get_gene_annotation(symbol: str) -> dict[str, Any]:
    """Retrieve locally reviewed annotation metadata for a gene symbol."""
    sym_clean = (symbol or "").strip().upper()
    if sym_clean in GENE_ANNOTATIONS:
        annotation = dict(GENE_ANNOTATIONS[sym_clean])
        annotation["structure_status"] = "curated_structure_mapping"
        annotation["structure_source"] = "RCSB Protein Data Bank"
        annotation["annotation_source"] = (
            "Local reviewed annotation panel; verify against current primary literature"
        )
        return annotation

    # Dynamic fallback for unlisted genes
    return {
        "symbol": sym_clean,
        "name": f"{sym_clean} Human Protein Target",
        "locus": "Genomic Locus",
        "ensembl_id": None,
        "uniprot_id": None,
        "pdb_id": None,
        "structure_status": "unavailable",
        "structure_source": None,
        "annotation_source": "No local reviewed annotation is available",
        "druggability": "Not described in the local target panel",
        "role": "Protein associated with the retrieved interaction network",
        "hotspots": [
            f"Amplification or increased activity reported for {sym_clean}",
            f"Reported variants in {sym_clean}",
            "Possible acquired-resistance association",
        ],
        "pathways": ["Reported protein interactions", "Cancer-related signaling"],
    }
